### ISSUE TITLE
Optimization for reduce frame drop

### ISSUE THREAD

**Issue by Sharlottes** [Sharlottes/Informatis#98]
frame drop is critical and fatal issue in Informatis.
I should save frames as possible as many, for better and optional user experience.

* [ ] solve setting R/W cost issue #95 
* [ ] some OverDraws seems calculating and drawing out of the screen. it's useless rendering so it shouldn't work. #96
* [ ] window ui supports responsive design by cleaning and rebuilding **every frame or seconds**. make it rebuilded when resizing is done.  #87 
* [ ] according to my feature tree, every features can be toggled. but some of features are not yet. #97
